spring.application.name=EcommerceAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce_user
spring.datasource.password=ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=oLmkMdgWv+BxrwoamZR0+MBJLaznEDbTaBps8g5ss3M9
jwt.expiration=86400000

